live_config_reload = true

[colors.bright]
black = "0x747369"
blue = "0x6699cc"
cyan = "0x66cccc"
green = "0x99cc99"
magenta = "0xcc99cc"
red = "0xf2777a"
white = "0xf2f0ec"
yellow = "0xffcc66"

[colors.normal]
black = "0x1e1e1e"
blue = "0x6699cc"
cyan = "0x66cccc"
green = "0x99cc99"
magenta = "0xcc99cc"
red = "0xf2777a"
white = "0xd3d0c8"
yellow = "0xffcc66"

[colors.primary]
background = "0x1e1e1e"
foreground = "0xd3c0c8"

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "IBM Plex Mono"
style = "Bold"

[font.italic]
family = "IBM Plex Mono"
style = "Italic"

[font.normal]
family = "IBM Plex Mono"
style = "Regular"

[font.offset]
x = 1
y = 1

[window.padding]
x = 5
y = 0

[selection]
save_to_clipboard = true
